"""Pydantic models used across the Airtable Analyzer application."""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field


class AirtableField(BaseModel):
    """Representation of an Airtable field."""

    model_config = ConfigDict(populate_by_name=True)

    id: str
    name: str
    type: str
    description: Optional[str] = None
    is_primary_field: bool = Field(default=False, alias="isPrimaryField")
    options: Optional[Dict[str, Any]] = None
    field_references: Optional[Dict[str, Any]] = Field(default=None, alias="fieldReferences")


class AirtableView(BaseModel):
    """Representation of an Airtable view."""

    model_config = ConfigDict(populate_by_name=True)

    id: str
    name: str
    type: Optional[str] = None
    description: Optional[str] = None
    field_order: Optional[Dict[str, Any]] = Field(default=None, alias="fieldOrder")
    filters: Optional[Dict[str, Any]] = None
    sorts: Optional[List[Dict[str, Any]]] = None
    groups: Optional[List[Dict[str, Any]]] = None


class AirtableTable(BaseModel):
    """Representation of an Airtable table including fields and views."""

    model_config = ConfigDict(populate_by_name=True)

    id: str
    name: str
    description: Optional[str] = None
    fields: List[AirtableField]
    views: List[AirtableView] = Field(default_factory=list)
    primary_field_id: Optional[str] = Field(default=None, alias="primaryFieldId")


class AirtableBaseSchema(BaseModel):
    """Full Airtable base metadata fetched from the API."""

    id: str
    name: str
    tables: List[AirtableTable]


class RelationshipSummary(BaseModel):
    """Summary of a relationship between two tables."""

    from_table_id: str
    from_table_name: str
    from_field_id: str
    from_field_name: str
    to_table_id: str
    to_table_name: str
    relationship_type: str
    configuration: Dict[str, Any]


class FieldSummary(BaseModel):
    """Processed view of a table field for downstream analysis."""

    id: str
    name: str
    type: str
    description: Optional[str]
    is_primary: bool
    configuration: Dict[str, Any]
    linked_table_id: Optional[str] = None
    linked_table_name: Optional[str] = None


class ViewSummary(BaseModel):
    """Processed view configuration."""

    id: str
    name: str
    type: Optional[str]
    description: Optional[str]
    visible_fields: List[str]
    filters: Optional[Dict[str, Any]]
    sorts: Optional[List[Dict[str, Any]]]
    groups: Optional[List[Dict[str, Any]]]


class TableSummary(BaseModel):
    """Processed summary of a table."""

    id: str
    name: str
    description: Optional[str]
    primary_field_id: Optional[str]
    fields: List[FieldSummary]
    views: List[ViewSummary]
    dependencies: List[str]


class SchemaAnalysis(BaseModel):
    """Aggregated details about a base schema for LLM consumption."""

    base_id: str
    base_name: str
    tables: List[TableSummary]
    relationships: List[RelationshipSummary]
    suggested_table_creation_order: List[str]


class DuplicationStep(BaseModel):
    """Single step in the duplication guide returned by Gemini."""

    order: int
    title: str
    description: str
    prerequisites: List[str] = Field(default_factory=list)


class DuplicationTableDetail(BaseModel):
    """Detailed duplication instructions per table."""

    table_name: str
    summary: str
    field_instructions: List[str]
    view_instructions: List[str]
    sequencing_notes: List[str]


class DuplicationGuide(BaseModel):
    """Structured response generated by Gemini."""

    base_overview: str
    key_considerations: List[str]
    table_details: List[DuplicationTableDetail]
    relationships: List[str]
    duplication_steps: List[DuplicationStep]
    post_duplication_checks: List[str]
